### ISSUE TITLE
[Steam Deck][1.4.1-steamos-beta] Error during installation

### ISSUE THREAD

**Issue by abalbanyan** [chyyran/skyinstaller#5]
Hello! I'm trying to use this mod on my Steam Deck but I've been unable to get it working. The installation will reach 100%, then stop without the voices being installed.

Reproduction:
1. I switched to Desktop Mode.
2. I opened up Steam and kept it open throughout the following steps.
3. I ran (copied from https://github.com/chyyran/skyinstaller/releases/tag/1.4.1-steamos-beta) this command in `Konsole`:
```
curl -L https://github.com/chyyran/skyinstaller/releases/download/1.4.1-steamos-beta/skyinstaller-steamos.tgz | tar xvz -C /tmp && chmod +x /tmp/skyinstaller && /tmp/skyinstaller
```
4. The installer opened up. I clicked "Install" for _Trails in the Sky_ (not SC or 3rd).
5. The installation will reach 100%, then I see the following error in the console:
```
[S_API] SteamAPI_Init(): Loaded '/home/deck/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 228980
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198029444965 [API loaded no]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Gameloop.Vdf.VdfTextReader.ReadToken()
   at Gameloop.Vdf.VdfSerializer.ReadProperty(VdfReader reader)
   at Gameloop.Vdf.VdfSerializer.ReadObject(VdfReader reader)
   at Gameloop.Vdf.VdfSerializer.ReadProperty(VdfReader reader)
   at Gameloop.Vdf.VdfSerializer.ReadObject(VdfReader reader)
   at Gameloop.Vdf.VdfSerializer.ReadProperty(VdfReader reader)
   at Gameloop.Vdf.VdfSerializer.Deserialize(TextReader textReader)
   at Gameloop.Vdf.VdfConvert.Deserialize(TextReader reader, VdfSerializerSettings settings)
   at Gameloop.Vdf.VdfConvert.Deserialize(String value, VdfSerializerSettings settings)
   at Gameloop.Vdf.VdfConvert.Deserialize(String value)
   at TrailsHelper.Models.SoraVoiceInstallModel.WriteSteamArgsOnLinux()
   at TrailsHelper.Models.SoraVoiceInstallModel.WriteSteamArgsOnLinux()
```

Thanks for making this mod! I'm hoping I'll be able to get it working on my Steam Deck. :)

**Comment by chyyran** [comment]
I’ll take a look at this soon, sorry for the delay.

**Comment by abalbanyan** [comment]
Thank you! I appreciate your work on this mod.

**Comment by vinaysshenoy** [comment]
I am running into this same problem with the beta release too. @abalbanyan Were you able to get it working? It reaches 100% and then there is this same error as you described.

**Comment by Gunoshozo** [comment]
The source of the issue is that default token size of `VdfConvert` may be too small for `localconfig.vdf`
And you need to do something like this:
```c#
long fileSize = new FileInfo(localConfigPath).Length;
int maxTokenSize = (int)fileSize / 10; // arbitrary maybe need to use some better heuristics
VdfSerializerSettings vdfSerializerSettings = new VdfSerializerSettings();
vdfSerializerSettings.MaximumTokenSize = maxTokenSize;
vdfSerializerSettings.UsesEscapeSequences = true;
var value = VdfConvert.Deserialize(localconfig, vdfSerializerSettings);
```

**Comment by chyyran** [comment]
Thanks for looking into it, I'll give that a shot, but I'm currently on vacation. If you could make a PR that might help get things moving quicker.

**Comment by Gunoshozo** [comment]
For those who are having the same issue you probably can just set 
```
WINEDLLOVERRIDES="dinput8=n,b" %command%
```
as your lanuch options for the game and it probably will just work

**Comment by chyyran** [comment]
This should be fixed by #9 and 1.5.0
